spring:
  application:
    name: digitalLibrary

#datasource:
#  url: jdbc:mysql://172.18.128.1:3307/spring_boot_test
#  username: springuser
#  password: Password@8041
#  driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: update
  show-sql: true
  
#debug: true

#    redis:
#      host: <your-host>
#      port: <your-port>
#      password: <your-password> [Optional]

security:
  user:
    name: "sudhanshu"
    password: "sudhanshu"